repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --extend-fixable=F401]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
