name: CI

on:
  pull_request:
  push:
    branches: [ repo_refactor ]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:${{ matrix.qgis-tags }}
    strategy:
      matrix:
        qgis-tags: [ release-3_28, release-3_34, latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip setuptools
          pip3 install -qr qgis_requirements.txt
          pip3 install -qr dev_requirements.txt
      - name: Run tests
        env:
          QGIS_IN_CI: 1
        run: >
          xvfb-run -s '+extension GLX -screen 0 1024x768x24'
          pytest -v --cov zonal_exact/tests -m 'not with_pytest_qt' -p no:pytest-qt tests

  code-style:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        - uses: pre-commit/action@v3.0.0
  