name: code style

on:
  pull_request:
  push:
    branches: [ repo_refactor ]

jobs:
  code-style:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        - uses: pre-commit/action@v3.0.0
  